name: github_analyzer_frontend
description: A comprehensive GitHub repository analyzer with AI-powered insights

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # UI & Visualizations
  fl_chart: ^0.64.0
  google_fonts: ^6.1.0
  
  # Utilities
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  
  # Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Icons & Assets
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # PWA Support
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
